@echo off
echo Downloading Arma 2...
steamcmd +login "devinpharris" "PartyFowl12#$1234" +force_install_dir e:\DayZ-Epoch\ +app_update "33910" validate +quit
echo Downloading Arma 2 OA...
steamcmd +login "devinpharris" "PartyFowl12#$1234" +force_install_dir e:\DayZ-Epoch\ +app_update "33930" validate +quit
echo Download Complete...