@echo off
echo Downloading Arma 2...
steamcmd +login "" "" +force_install_dir e:\DayZ-Epoch\ +app_update "33910" validate +quit
echo Downloading Arma 2 OA...
steamcmd +login "" "" +force_install_dir e:\DayZ-Epoch\ +app_update "33930" validate +quit
echo Download Complete...
echo Copying Configuration Files...
copy E:\DayZ-Epoch\Config-Examples\DayZ_Epoch_instance_11_Chernarus.bat E:\DayZ-Epoch\
xcopy E:\DayZ-Epoch\Config-Examples\instance_11_Chernarus E:\DayZ-Epoch\instance_11_Chernarus\